### ISSUE TITLE
xtext-maven-plugin fails on Jenkins

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-emf-parsley/emf-parsley#47]
```
[ERROR] Failed to execute goal org.eclipse.xtext:xtext-maven-plugin:2.29.0:generate (default) on project org.eclipse.emf.parsley.tests.views: Execution default of goal org.eclipse.xtext:xtext-maven-plugin:2.29.0:generate failed: Unable to create injector, see the following errors:
[ERROR] 
[ERROR] 1) [Guice/ErrorInjectingConstructor]: NoClassDefFoundError: org/eclipse/ui/IViewPart
[ERROR]   at EmfParsleyDslExpectedSuperTypes.<init>(EmfParsleyDslExpectedSuperTypes.java:61)
[ERROR]   at EmfParsleyDslExpectedSuperTypes.class(EmfParsleyDslExpectedSuperTypes.java:59)
[ERROR]   at EmfParsleyDslValidator._emfParsleyDslExpectedSuperTypes(EmfParsleyDslValidator.java:65)
[ERROR]       \_ for field _emfParsleyDslExpectedSuperTypes
[ERROR]   at MethodBasedModule.configure(MethodBasedModule.java:58)
[ERROR]   while locating EmfParsleyDslValidator
```

can it be a Maven problem?

**Comment by LorenzoBettini** [comment]
Yes, it was Maven. It doesn't work with Maven 3.8.5, but it does with 3.8.6. Better switch to the Maven wrapper!
